auth_app/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView

from auth_app.forms import ClientCreationForm
from auth_app.views import AccountCabinet, CabinetOrderDetail



urlpatterns = [
    url(r'^login/', LoginView.as_view(
        template_name='auth_app/login.html'),
        name='login'),

    url(r'^logout/', LogoutView.as_view(next_page='/'), name='logout'),

    url(r'^register/', CreateView.as_view(
        template_name='auth_app/register.html',
        form_class=ClientCreationForm,
        success_url='/'),
        name='register'),

    url(r'^cabinet/(?P<pk>\d+)/$',AccountCabinet.as_view(template_name='auth_app/cabinet.html'), name='cabinet'),
    url(r'^orders/(?P<pk>\d+)/(?P<cart_id>\d+)/',CabinetOrderDetail.as_view(template_name='auth_app/account_order_detail.html'), name='order')
]

cart/urls.py
from django.conf.urls import url
from cart.views import get_cart, add_to_cart, remove_from_cart ,redirect_to_order


urlpatterns = [
    url(r'^(?P<user_id>\d+)/$', get_cart, name='get'),
    url(r'^add/(?P<product_id>\d+)/(?P<quantity>\d+)/$', add_to_cart, name='add'),
    url(r'^remove/(?P<product_id>\d+)/$', remove_from_cart, name='remove'),
    url(r'^set/(?P<user_id>\d+)/(?P<cart_id>\d+)/$', redirect_to_order, name='set')
]

shop_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

from auth_app import urls as auth_urls
from catalog import urls as catalog_urs
from cart import urls as cart_urls
from order import urls as order_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='catalog/home_page.html'), name='home'),
    url(r'^catalog/', include(catalog_urs, namespace='catalog')),
    url(r'^account/', include(auth_urls, namespace='account')),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^order/', include(order_urls, namespace='order'))
]

auth_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class ClientUser(AbstractUser):
    comment_note = models.CharField(max_length=120, blank=True)

auth_app/forms.py
from django.contrib.auth.forms import UserCreationForm

from auth_app.models import ClientUser

class ClientCreationForm(UserCreationForm):
    class Meta:
        model = ClientUser
        fields = ('username','first_name','last_name')

auth_app/views.py
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from order.models import ProductOrder
from .models import ClientUser
from cart.models import Item


class AccountCabinet(LoginRequiredMixin, DetailView):
    """
    Личный кабинет с заказами
    """
    login_url = '/auth/login'
    model = ClientUser


    def get_context_data(self, *args, **kwargs):
        context = super(AccountCabinet, self).get_context_data(*args, **kwargs)
        context['orders'] = ProductOrder.objects.filter(customer_id=self.kwargs.get('pk'))
        return context


class CabinetOrderDetail(DetailView):
    """
    Информация по заказу
    """
    model = Item

    def get_context_data(self, *args, **kwargs):
        context = super(CabinetOrderDetail, self).get_context_data(*args, **kwargs)
        context['order'] = ProductOrder.objects.get(pk=self.kwargs.get('pk'))
        context['items'] = Item.objects.filter(cart=self.kwargs.get('cart_id'))
        return context

auth_app/templates/auth_app/account_order_detail.html
{% extends 'auth_app/cabinet.html' %}

{% block user_order %}
<h3>Заказ №{{order.id}} от {{order.created_date}}</h3>

 <table class="table table-bordered">
            <tr>
                <th>Название продукта</th>

                <th>Количество</th>
            </tr>
            {% for item in items %}
            <tr>
                <td>{{ item.product.name }}</td>
                <td>{{ item.quantity }}</td>
            </tr>
            {% endfor %}
        </table>

<h3>Адрес доставки: {{order.address}}</h3>
<h3>Время доставки: {{order.delivery_time}}</h3>
<h3>Комментарий к заказу: {{order.comment}}</h3>
<p><a href="{% url 'account:cabinet' pk=user.id  %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true"> Вернуться в личный кабинет</a></p>


{% endblock %}

auth_app/templates/auth_app/cabinet.html
{% extends 'catalog/_base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-5">

        <h2>Личный кабинет!</h2>


        <h3>Привет, {{user.username}}</h3>


        <p>Ваши заказы</p>
            {% for order in orders %}
            <h3><a href="{% url 'account:order' pk=order.id cart_id=order.cart_id%}">{{order}}</a></h3>
            {% endfor%}

            {% block user_order%}
            {% endblock%}

    </div>

    <div class="col-sm-1">

    </div>
</div>




{% endblock %}

auth_app/templates/auth_app/login.html
{% extends 'catalog/_base.html' %}

{% block content %}

<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-7">
        <h3>Введите свои учетные данные</h3>
        <form action="{% url 'account:login' %}" method="post">
            {%csrf_token%}
            {{form.as_p}}
            <button type="submit">Войти</button>
        </form>
    </div>
    <div class="col-sm-3"></div>
</div>


{% endblock %}

auth_app/templates/auth_app/register.html
{% extends 'catalog/_base.html' %}

{% block content %}

<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-7">
        <h3>Введите свои данные</h3>
        <form action="{% url 'account:register' %}" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Подтвердить">
        </form>
    </div>
</div>

{% endblock %}