auth_app/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView

from auth_app.forms import ClientCreationForm
from auth_app.views import AccountCabinet, CabinetOrderDetail



urlpatterns = [
    url(r'^login/', LoginView.as_view(
        template_name='auth_app/login.html'),
        name='login'),

    url(r'^logout/', LogoutView.as_view(next_page='/'), name='logout'),

    url(r'^register/', CreateView.as_view(
        template_name='auth_app/register.html',
        form_class=ClientCreationForm,
        success_url='/'),
        name='register'),

    url(r'^cabinet/(?P<pk>\d+)/$',AccountCabinet.as_view(template_name='auth_app/cabinet.html'), name='cabinet'),
    url(r'^orders/(?P<pk>\d+)/(?P<cart_id>\d+)/',CabinetOrderDetail.as_view(template_name='auth_app/account_order_detail.html'), name='order')
]

cart/urls.py
from django.conf.urls import url
from cart.views import get_cart, add_to_cart, remove_from_cart ,redirect_to_order


urlpatterns = [
    url(r'^(?P<user_id>\d+)/$', get_cart, name='get'),
    url(r'^add/(?P<product_id>\d+)/(?P<quantity>\d+)/$', add_to_cart, name='add'),
    url(r'^remove/(?P<product_id>\d+)/$', remove_from_cart, name='remove'),
    url(r'^set/(?P<user_id>\d+)/(?P<cart_id>\d+)/$', redirect_to_order, name='set')
]

catalog/urls.py
from django.conf.urls import url
from catalog.views import (
    ProductDetailView,
    ProductCategoryListView
    )


urlpatterns = [
    url(r'^category/(?P<category_id>\d+)/', ProductCategoryListView.as_view(), name='category'),
    url(r'^(?P<product_id>\d+)/', ProductDetailView.as_view(), name='detail'),
]

shop_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

from auth_app import urls as auth_urls
from catalog import urls as catalog_urs
from cart import urls as cart_urls
from order import urls as order_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='catalog/home_page.html'), name='home'),
    url(r'^catalog/', include(catalog_urs, namespace='catalog')),
    url(r'^account/', include(auth_urls, namespace='account')),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^order/', include(order_urls, namespace='order'))
]

catalog/models.py
from django.db import models
from django.db.models import Manager


class ProductAvailableManager(Manager):
    # Только доступные товары
    def get_queryset(self, **kwargs):
        return super().get_queryset().filter(
            is_available=True
        )



class Product(models.Model):

    name = models.CharField(max_length=50)
    description = models.TextField(max_length=400, null=True)
    weight = models.CharField(max_length=50, null=True)
    price = models.DecimalField(max_digits=10,decimal_places=2, null=True)
    quantity = models.PositiveIntegerField(verbose_name='quantity')
    is_available = models.BooleanField(default=True)

    has_variants = models.BooleanField(default=False)

    product_type = models.ForeignKey('ProductType', related_name='products')

    objects = Manager()
    available_objects = ProductAvailableManager()

    def __str__(self):
        return self.name

#
#     пока не реализовано - варианты товаров по весу
#
# class ProductVariant(models.Model):
#
#     product = models.ForeignKey('Product', related_name='product_vars')
#     weight_override = models.ForeignKey('ProductWeight', related_name='product_variants')
#     name = models.CharField(max_length=50)
#     price_override = models.DecimalField(max_digits=10, decimal_places=2, null=True)
#
#
#     objects = Manager()
#
#     def __str__(self):
#         return self.name


class ProductWeight(models.Model):
    # вес тип
    weight = models.CharField(max_length=10)

    def __str__(self):
        return '{} g'.format(self.weight)


class ProductType(models.Model):
    # тип продукта (например, арабика)
    title = models.CharField(max_length=50)

    category = models.ForeignKey('Category', related_name='product_type')

    def __str__(self):
        return self.title


class Category(models.Model):
    # категория товара (например, кофе)
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title





















































#
# class Product(models.Model):
#     name = models.CharField(max_length=50)
#     description = models.TextField(max_length=400, null=True)
#
#     size_variants = models.BooleanField(default=True)
#
#
#
#     type = models.ForeignKey('ProductType', related_name='products')
#
#     size = models.ForeignKey('ProductPackageSize', related_name='products')
#
#     price =
#     is_available = models.BooleanField(default=True)
#
#
#
#
#
# class IsAvailableManager(models.Manager):
#     def get_queryset(self,**kwargs):
#         return super().get_queryset().filter(
#             is_available=True,
#         )
#
#
# class ProductSize(models.Model):
#     SMALL = ('S', '250g')
#     MEDIUM = ('M', '500g')
#     LARGE = ('L', '1kg')
#
#     __sizes = dict([SMALL, MEDIUM, LARGE])
#
#     product_size = models.CharField(max_length=1, choices=__sizes.items())
#
#     def __str__(self):
#         return str(self.__sizes[self.product_size])
#
#
# class ProductType(models.Model):
#     title = models.CharField(max_length=50)
#     category = models.ForeignKey('Category', related_name='+')
#
#
#
#
#
#
#
#
# class Product(models.Model):
#
#     name = models.CharField(max_length=120)
#     description = models.TextField(max_length=500, null=True)
#     product_type = models.ForeignKey('ProductType', related_name='product_type')
#
#
#     price = models.DecimalField(max_digits=10,decimal_places=2)
#     is_available = models.BooleanField(default=True)
#
#     def __str__(self):
#         return self.name
#
#     @property
#     def price(self):
#         return "RUB%s" % self.price
#
#     objects = Manager()
#     available_object = IsAvailableManager()
#
#
# class Category(models.Model):
#     title = models.CharField(max_length=100)
#
#     objects = Manager()
#
#     def __str__(self):
#         return self.title
#
# #
# # class ProductWeight(models.Model):
# #     SMALL = ('S', 'Small')
# #     MEDIUM = ('M', 'Medium')
# #     LARGE = ('L', 'Large')
# #     EXTRA_LARGE = ('XL','Extra Large')
# #     __all = dict([SMALL, MEDIUM, LARGE, EXTRA_LARGE])
# #
# #     size_shortcut = models.CharField(max_length=2, choices=__all.items())
# #     size_weight = models.IntegerField(max_length=3, choices= v[3] in __all.items())
# #
#
#
#
#

catalog/views.py
from django.shortcuts import  get_object_or_404
from django.views.generic import ListView, DetailView

from .models import Product


class ProductCategoryListView(ListView):
    template_name = 'catalog/product_category_list.html'
    queryset = Product.objects.select_related().select_related().all()

    def get_context_data(self, *args, **kwargs):
        context = super(ProductCategoryListView, self).get_context_data(*args, **kwargs)
        context['products'] = ProductCategoryListView.queryset.filter(product_type__category_id=self.kwargs.get("category_id"))
        return context



class ProductDetailView(DetailView):
    queryset = Product.objects.all()

    def get_object(self, queryset=queryset):
        product_id = self.kwargs.get("product_id")
        obj = get_object_or_404(Product, pk=product_id)
        return obj

catalog/templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
    .jumbotron {
        background-color: #fff;
        margin-bottom: 0;
    }

    .flex-container {
        display: flex;
        flex-wrap: wrap;
    }

    .navbar {
        margin-bottom: 50px;
        border-radius: 0;
    }

    body {
	position: relative;
	height: 100%;
}

.carousel-inner{
	max-height: 450px;
}

.swiper-slide {
	font-size: 16px;
	text-align: center;
	max-width: 250px;
}

.swiper-slide img {
	-moz-border-radius: 100px; /* Firefox */
	-webkit-border-radius: 100px; /* Safari, Chrome */
	-khtml-border-radius: 100px; /* KHTML */
	border-radius: 100px; /* CSS3 */
}

.greenfooter {
	text-align: center;
	background-color: #d4e5ce;
}

.advt {

}
.navbar{
        margin-bottom: 0!important;
    }


</style>

catalog/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

catalog/templates/snippets/nav.html
{#<nav class="navbar navbar-inverse">#}
{#  <div class="container-fluid">#}
{##}
{#    <div class="col-sm-5"></div>#}
{#    <div class="collapse navbar-collapse" id="myNavbar">#}
{#      <ul class="nav navbar-nav">#}
{#        <li class="active"><a href="/"><i class="fa fa-home fa-lg" aria-hidden="true"></i></a></li>#}
{#        <li class="nav-li"><a href="{% url 'catalog:category' category_id=1 %}">Чай</a></li>#}
{#        <li class="nav-item"><a href="{% url 'catalog:category' category_id=2 %}">Кофе</a></li>#}
{#      </ul>#}
{#      </ul>#}
{#    </div>#}
{#  </div>#}
{#</nav>#}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/"><i class="fa fa-home fa-lg" aria-hidden="true"></i></a></li>
                <li class="nav-li"><a href="{% url 'catalog:category' category_id=1 %}">Чай</a></li>
                <li class="nav-item"><a href="{% url 'catalog:category' category_id=2 %}">Кофе</a></li>
                <li class="nav-item"><a href="{% url 'catalog:category' category_id=3 %}">Пустая категория</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="">О нас</a></li>
                        <li><a href="#">Пустая ссылка</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="http://bootstrap-4.ru/">К сайту bootstrap</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Еще одна пустая ссылка</a></li>
                    </ul>
                </li>
            </ul>
              <ul class="nav navbar-nav navbar-right">
                  {% if user.is_authenticated%}
                <li><a href="{% url 'account:cabinet' pk=user.id %}"><i class="fa fa-user-circle-o" aria-hidden="true"></i>  Привет, {{ user }}! </a></li>
                <li><a href="{% url 'account:logout' %}">Выйти</a></li>
                <li><a href="{% url 'cart:get' user_id=user.id%}"><i class="fa fa-cart-plus fa-lg" aria-hidden="true"></i> Cart</a></li>
                  {% else %}
                <li><a href="{% url 'account:login'%}"><i class="fa fa-user fa-lg" aria-hidden="true"></i>  Войти </a></li>
                <li><a href="{% url 'account:register'%}"><i class="fa fa-user-plus" aria-hidden="true"></i>  Регистрация </a></li>
                  {% endif %}
              </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>