cart/urls.py
from django.conf.urls import url
from cart.views import get_cart, add_to_cart, remove_from_cart ,redirect_to_order


urlpatterns = [
    url(r'^(?P<user_id>\d+)/$', get_cart, name='get'),
    url(r'^add/(?P<product_id>\d+)/(?P<quantity>\d+)/$', add_to_cart, name='add'),
    url(r'^remove/(?P<product_id>\d+)/$', remove_from_cart, name='remove'),
    url(r'^set/(?P<user_id>\d+)/(?P<cart_id>\d+)/$', redirect_to_order, name='set')
]

catalog/urls.py
from django.conf.urls import url
from catalog.views import (
    ProductDetailView,
    ProductCategoryListView
    )


urlpatterns = [
    url(r'^category/(?P<category_id>\d+)/', ProductCategoryListView.as_view(), name='category'),
    url(r'^(?P<product_id>\d+)/', ProductDetailView.as_view(), name='detail'),
]

shop_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

from auth_app import urls as auth_urls
from catalog import urls as catalog_urs
from cart import urls as cart_urls
from order import urls as order_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='catalog/home_page.html'), name='home'),
    url(r'^catalog/', include(catalog_urs, namespace='catalog')),
    url(r'^account/', include(auth_urls, namespace='account')),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^order/', include(order_urls, namespace='order'))
]

catalog/models.py
from django.db import models
from django.db.models import Manager


class ProductAvailableManager(Manager):
    # Только доступные товары
    def get_queryset(self, **kwargs):
        return super().get_queryset().filter(
            is_available=True
        )



class Product(models.Model):

    name = models.CharField(max_length=50)
    description = models.TextField(max_length=400, null=True)
    weight = models.CharField(max_length=50, null=True)
    price = models.DecimalField(max_digits=10,decimal_places=2, null=True)
    quantity = models.PositiveIntegerField(verbose_name='quantity')
    is_available = models.BooleanField(default=True)

    has_variants = models.BooleanField(default=False)

    product_type = models.ForeignKey('ProductType', related_name='products')

    objects = Manager()
    available_objects = ProductAvailableManager()

    def __str__(self):
        return self.name

#
#     пока не реализовано - варианты товаров по весу
#
# class ProductVariant(models.Model):
#
#     product = models.ForeignKey('Product', related_name='product_vars')
#     weight_override = models.ForeignKey('ProductWeight', related_name='product_variants')
#     name = models.CharField(max_length=50)
#     price_override = models.DecimalField(max_digits=10, decimal_places=2, null=True)
#
#
#     objects = Manager()
#
#     def __str__(self):
#         return self.name


class ProductWeight(models.Model):
    # вес тип
    weight = models.CharField(max_length=10)

    def __str__(self):
        return '{} g'.format(self.weight)


class ProductType(models.Model):
    # тип продукта (например, арабика)
    title = models.CharField(max_length=50)

    category = models.ForeignKey('Category', related_name='product_type')

    def __str__(self):
        return self.title


class Category(models.Model):
    # категория товара (например, кофе)
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title





















































#
# class Product(models.Model):
#     name = models.CharField(max_length=50)
#     description = models.TextField(max_length=400, null=True)
#
#     size_variants = models.BooleanField(default=True)
#
#
#
#     type = models.ForeignKey('ProductType', related_name='products')
#
#     size = models.ForeignKey('ProductPackageSize', related_name='products')
#
#     price =
#     is_available = models.BooleanField(default=True)
#
#
#
#
#
# class IsAvailableManager(models.Manager):
#     def get_queryset(self,**kwargs):
#         return super().get_queryset().filter(
#             is_available=True,
#         )
#
#
# class ProductSize(models.Model):
#     SMALL = ('S', '250g')
#     MEDIUM = ('M', '500g')
#     LARGE = ('L', '1kg')
#
#     __sizes = dict([SMALL, MEDIUM, LARGE])
#
#     product_size = models.CharField(max_length=1, choices=__sizes.items())
#
#     def __str__(self):
#         return str(self.__sizes[self.product_size])
#
#
# class ProductType(models.Model):
#     title = models.CharField(max_length=50)
#     category = models.ForeignKey('Category', related_name='+')
#
#
#
#
#
#
#
#
# class Product(models.Model):
#
#     name = models.CharField(max_length=120)
#     description = models.TextField(max_length=500, null=True)
#     product_type = models.ForeignKey('ProductType', related_name='product_type')
#
#
#     price = models.DecimalField(max_digits=10,decimal_places=2)
#     is_available = models.BooleanField(default=True)
#
#     def __str__(self):
#         return self.name
#
#     @property
#     def price(self):
#         return "RUB%s" % self.price
#
#     objects = Manager()
#     available_object = IsAvailableManager()
#
#
# class Category(models.Model):
#     title = models.CharField(max_length=100)
#
#     objects = Manager()
#
#     def __str__(self):
#         return self.title
#
# #
# # class ProductWeight(models.Model):
# #     SMALL = ('S', 'Small')
# #     MEDIUM = ('M', 'Medium')
# #     LARGE = ('L', 'Large')
# #     EXTRA_LARGE = ('XL','Extra Large')
# #     __all = dict([SMALL, MEDIUM, LARGE, EXTRA_LARGE])
# #
# #     size_shortcut = models.CharField(max_length=2, choices=__all.items())
# #     size_weight = models.IntegerField(max_length=3, choices= v[3] in __all.items())
# #
#
#
#
#

catalog/views.py
from django.shortcuts import  get_object_or_404
from django.views.generic import ListView, DetailView

from .models import Product


class ProductCategoryListView(ListView):
    template_name = 'catalog/product_category_list.html'
    queryset = Product.objects.select_related().select_related().all()

    def get_context_data(self, *args, **kwargs):
        context = super(ProductCategoryListView, self).get_context_data(*args, **kwargs)
        context['products'] = ProductCategoryListView.queryset.filter(product_type__category_id=self.kwargs.get("category_id"))
        return context



class ProductDetailView(DetailView):
    queryset = Product.objects.all()

    def get_object(self, queryset=queryset):
        product_id = self.kwargs.get("product_id")
        obj = get_object_or_404(Product, pk=product_id)
        return obj

catalog/templates/catalog/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include 'snippets/css.html' %}
    <title>{% block title %}Shop{% endblock %}</title>

</head>
{% load static %}
<body>

{% include 'snippets/nav.html' %}

{% block content %}

{% endblock%}

{% include 'snippets/js.html' %}

{% block bottom %}

{% endblock %}
</body>
</html>

catalog/templates/catalog/home_page.html
{% extends 'catalog/_base.html' %}

{% load static %}

{% block content %}

<div id="carousel" class="carousel slide">
    <!--Slide IMG-->
    <div class="carousel-inner">
        <div class="item active">
            <img src="{% static 'catalog/mainfirstslider.jpg' %}" alt="slider-woman">
            <div class="carousel-caption font-slider">

                <div class="content">
                    <div class="row">
                        <div class="col-md-6 col-sm-8 col-xs-10">

                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="item">
            <img src="{% static 'catalog/mainsecondslider.jpg' %}" alt="slider-woman"> <!--/IMG/-->
        </div>
        <div class="item">
            <img src="{% static 'catalog/mainthirdslider.jpg' %}" alt="slider-woman"> <!--/IMG/-->
        </div>

  </div>
    <!--Slide button -->
    <a href="#carousel" class="left carousel-control" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a href="#carousel" class="right carousel-control" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>

    <hr\>

    <div class="container w">
    <div class="row centered">
        <br><br>
        <div class="col-lg-3">
            <i class="fa fa-heart fa-3x centered"></i>
            <h4>Вкус</h4>
            <p>
                Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне.
                Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века.
            </p>
        </div>
        <div class="col-lg-3">
            <i class="fa fa-laptop fa-3x"></i>
            <h4>Преимущества</h4>
            <p>
                Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне.
                Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века.
            </p>
        </div>
        <div class="col-lg-3">
            <i class="fa fa-shield fa-3x"></i>
            <h4>Гарантия</h4>
            <p>
                Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне.
                Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века.
            </p>
        </div>
        <div class="col-lg-3">
            <i class="fa fa-shield fa-3x"></i>
            <h4>Натурально</h4>
            <p>
                Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне.
                Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века.
            </p>
        </div>
        <br><br>
    </div>
</div>

        <div class="container w">
    <div class="row centered">
        <br><br>
        <div class="col-lg-3 text-center">
            <h4>Зеленый чай</h4>
            <img src="{% static 'catalog/tea1.jpg' %}">
        </div>
        <div class="col-lg-3 text-center">
            <h4>Черный чай</h4>
            <img src="{% static 'catalog/tea1.jpg' %}">
        </div>
        <div class="col-lg-3 text-center">
            <h4>Красный чай</h4>
           <img src="{% static 'catalog/tea1.jpg' %}">
        </div>
        <div class="col-lg-3 text-center">
            <h4>Белый чай</h4>
           <img src="{% static 'catalog/tea1.jpg' %}">
        </div>
        <br><br>
    </div>
</div>


{% endblock %}

{% block bottom %}

    <div  class="greenfooter">
        <p style="margin-top: 4px;">Как к нам добраться</p>
    <p style="font-size: 12px; margin-bottom: 0px; margin-top: -10px;">
        <a target="_blank" href="#">Яндекс карта</a>
    </p>
</div>
</div>
<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A79b14dfd98bfbf113729dca0bdd90d3bdf9334afb2ea459dbb08ed6c63713187&amp;width=100%25&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>    <div class="greenfooter">
    <div  class="greenfooter">
        <p style="margin-top: 4px;">Супер чай</p>
    <p style="font-size: 12px; margin-bottom: 0px; margin-top: -10px;">
        <a target="_blank" href="#">Пользовательское соглашение</a>
    </p>
</div>
{% endblock %}

catalog/templates/catalog/product_category_list.html
{% extends 'catalog/_base.html' %}

{% load static %}

{% block content %}
    <div class="container w">
        <div class="row centered">

                {% for product in products%}

                                <div class="col-lg-3 text-center">
                                    <h4><a href="{% url 'catalog:detail' product_id=product.id %}">{{product.name}}</a></h4>
                                    {% with cat_val=product.product_type.category_id%}
                                        {% if cat_val == 1%}
                                        <img src="{% static 'catalog/oolong_tea.jpg' %}" class="img-responsive" style="width:100%" alt="Second slide"/>
                                                                                    <p>{{product.description}}</p>
                                        <h4>Цена: {{product.price}}</h4>
                                        {% else %}
                                        <img src="{% static 'catalog/coffe_grains.jpg' %}" class="img-responsive" style="width:100%" alt="Second slide"/>
                                                                                    <p>{{product.description}}</p>
                                        <h4>Цена: {{product.price}}</h4>
                                        {% endif %}
                                        {% endwith %}

                                </div>
                {%endfor%}
        </div>
    </div>


{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/_base.html' %}

{% load static %}

{% block content %}

<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-3">
        {% if object.product_type.category_id == 1 %}
        <img src="{% static 'catalog/oolong_tea.jpg' %}" class="img-responsive" style="width:100%" alt="Second slide"/>
        {% else %}
        <img src="{% static 'catalog/coffe_grains.jpg' %}" class="img-responsive" style="width:100%" alt="Second slide"/>
        {% endif %}
    </div>
    <div class="col-sm-4">
            <div class="panel">
                <div class="panel-heading" align="center">
                    <h1>{{ object.name }}</h1>
                    <p>{{ object.product_type}}</p>
                </div>
                <div class="panel-body">{{object.description}}</div>
                {% if user.is_authenticated%}
                <div class="panel-footer" align="center">
                    <a href="{% url 'cart:add' product_id=object.id quantity=object.quantity %}"><i class="fa fa-plus-square-o fa-4x" aria-hidden="true"></i></a>
                    <a href="{% url 'cart:remove' product_id=object.id %}"><i class="fa fa-minus-square-o fa-4x" aria-hidden="true"></i></a>
                    {% for message in messages %}
                    <h3 {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{message}}</h3>
                    {% endfor %}
                </div>

                {% endif %}
            </div>
    <p align="center"><a href="{% url 'catalog:category' category_id=object.product_type.category_id %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true"> Вернуться назад</a></p>
    </div>
</div>


{% endblock %}